
newIssueWelcomeComment: |
  Thanks for digging in and opening an Issue here. Resuminator is awesome because of people like you. 
  
  ![Investigate](https://media.giphy.com/media/5n26EW5p9lWGafPdbf/giphy.gif)
  
  Make sure to follow Issue Template & [Contributing Guidelines](https://docs.resuminator.in/docs/developer-guide/contributing)! 


newPRWelcomeComment: |
  Thanks for going the extra mile and opening this PR! 
  
  ![toast](https://media.giphy.com/media/8Iv5lqKwKsZ2g/giphy.gif)
  
  Make sure to complete PR Template and Read our [Contributing Guidelines](https://docs.resuminator.in/docs/developer-guide/contributing)! 
  


firstPRMergeComment: |
  Congrats on merging your first pull request! We here at Resuminator are proud of you! 
  
  ![congrats](https://media.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif)
  
  



