export const USERINFO = { ADD: "ADD_USERINFO", REMOVE: "REMOVE_USERINFO" };
export const EXPERIENCE_INFO = {ADD: "ADD_EXPERIENCE_INFO", UPDATE: "UPDATE_EXPERIENCE_INFO", DELETE: "DELETE_EXPERIENCE_INFO"};
export const EDUCATION_INFO = {ADD: "ADD_EDUCATION_INFO", UPDATE: "UPDATE_EDUCATION_INFO", DELETE: "DELETE_EDUCATION_INFO"};
