/*
 * Copyright Vivek Nigam, 2020
 * Licensed under the GNU General Public License, Version 3.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * Authors:
 * - Vivek Nigam, <viveknigam.nigam3@gmail.com>, 2020
 */

export const USERINFO = {
  ADD: "ADD_USERINFO",
  REMOVE: "REMOVE_USERINFO",
  FETCH_REQUEST: "FETCH_USERINFO_REQUEST",
  FETCH_SUCCESS: "FETCH_USERINFO_SUCCESS",
  FETCH_ERROR: "FETCH_USERINFO_FAILURE",
};
export const EXPERIENCE_INFO = {
  ADD: "ADD_EXPERIENCE_INFO",
  UPDATE: "UPDATE_EXPERIENCE_INFO",
  DELETE: "DELETE_EXPERIENCE_INFO",
  FETCH_REQUEST: "FETCH_EXPERIENCE_INFO_REQUEST",
  FETCH_SUCCESS: "FETCH_EXPERIENCE_INFO_SUCCESS",
  FETCH_ERROR: "FETCH_EXPERIENCE_INFO_FAILURE",
  ADD_REQUEST: "ADD_EXPERIENCE_INFO_REQUEST",
  ADD_SUCCESS: "ADD_EXPERIENCE_INFO_SUCCESS",
  ADD_ERROR: "ADD_EXPERIENCE_INFO_FAILURE",
};
export const EDUCATION_INFO = {
  ADD: "ADD_EDUCATION_INFO",
  UPDATE: "UPDATE_EDUCATION_INFO",
  DELETE: "DELETE_EDUCATION_INFO",
};
export const CERTIFICATION_INFO = {
  ADD: "ADD_CERTIFICATION_INFO",
  UPDATE: "UPDATE_CERTIFICATION_INFO",
  DELETE: "DELETE_CERTIFICATION_INFO",
};
export const PROJECT_INFO = {
  ADD: "ADD_PROJECT_INFO",
  UPDATE: "UPDATE_PROJECT_INFO",
  DELETE: "DELETE_PROJECT_INFO",
};
export const SKILL_INFO = {
  ADD: "ADD_SKILL_INFO",
  DELETE: "DELETE_SKILL_INFO",
  DISPLAY_TYPE: "SET_DISPLAY_TYPE",
};
export const VIEW = { TOGGLE: "TOGGLE_VIEW" };
export const APP = {
  INIT_REQUEST: "APP_INIT_REQUEST",
  INIT_SUCCESS: "APP_INIT_SUCCESS",
  INIT_FAILURE: "APP_INIT_FAILURE",
};
